name: Consultant
version: 0.2.5
downloadUrl: https://www.npmjs.com/package/consultant-cli
license: BSD License
licenseUrl: https://opensource.org/licenses/BSD-3-Claus

headerLinks:
  - title: GitHub
    url: https://github.com/Jense5/consultant

footerLinks:
  - title: GitHub
    url: https://github.com/Jense5/consultant
  - title: Issues
    url: https://github.com/Jense5/consultant/issues

header:
  color1: "#34495e"
  color2: "#3498db"
  trianglify: false

analytics:
  account: UA-43675030-4
  domain: auto

github:
  url: https://consultant.js.org

githubButton:
  user: jense5
  repo: consultant

twitter:
  enabled: true
  via:
  hash: consultantcli
  account:

exclude: ['README.md', 'LICENSE', 'bower.json', 'Gemfile.lock', 'Gemfile']

gems:
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
  - jekyll-sitemap
